---
- name: Terminal Provision
  hosts: terminals
  gather_facts: true
  become: true 
  vars_files:
    - vars.yml
  roles:
    # - { role: apt }
    # - { role: python }
    - { role: provision }
    # - { role: terminal_setup }
    # - { role: pt_agent_client }
    # - { role: systemd_service }