---
- name: Copy socketio client file
  copy:
    src: /home/may/Documents/work/project/ansible_project/Pip_Ansible/roles/socketio/files/pt_agent-0.1.0.tar.gz
    dest: /home/frontiir/pt_agent-0.1.0.tar.gz

- name: Extract socketio client file
  unarchive:
    src: /home/frontiir/pt_agent-0.1.0.tar.gz
    dest: /home/frontiir/
    remote_src: yes

- name: Set Permissions
  file:
    path: "/home/frontiir/pt_agent-0.1.0"
    mode: "777"

- name: Set owner and group
  file:
    path: "/home/frontiir/pt_agent-0.1.0"
    owner: frontiir
    group: frontiir

- name: Remove zip file
  file:
    path: /home/frontiir/pt_agent-0.1.0.tar.gz
    state: absent

- name: Copy wheel files
  copy:
    src: /home/may/Documents/work/project/ansible_project/Pip_Ansible/roles/socketio/files/wheels/
    dest: /home/frontiir/pt_agent-0.1.0/

- name: Copy package wheel file
  copy:
    src: /home/may/Documents/work/project/ansible_project/Pip_Ansible/roles/socketio/files/pt_agent-0.1.0-py3-none-any.whl
    dest: /home/frontiir/pt_agent-0.1.0/

- name: Create Python virtual environment for pt_agent
  shell: |
    cd /home/frontiir/pt_agent-0.1.0/
    python3.8 -m venv .venv
  become: false

- name: Activate Python virtual environment and install the package for pt_agent
  shell: |
    /home/frontiir/pt_agent-0.1.0/.venv/bin/python -m pip install /home/frontiir/pt_agent-0.1.0/pt_agent-0.1.0-py3-none-any.whl
  become: true
  register: install_result  # Capture the result of the installation

- name: Display installation output (for debugging)
  debug:
    var: install_result.stdout_lines
  when: install_result.stdout_lines is defined and install_result.stdout_lines | length > 0

- name: Set .venv owner and group
  file:
    path: "/home/frontiir/pt_agent-0.1.0/.venv"
    owner: frontiir
    group: frontiir
    recurse: yes

- name: Create a service file for pt-agent
  copy:
    content: |
      [Unit]
      Description=Provisioning CPE Agent SocketIO Client
      After=network.target

      [Service]
      WorkingDirectory=/home/frontiir/pt_agent-0.1.0
      ExecStart=/home/frontiir/pt_agent-0.1.0/client
      ExecReload=/usr/bin/kill -s HUP $MAINPID
      ExecStop=/usr/bin/kill -s TERM $MAINPID
      Restart=on-failure

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/pt-agent.service
  notify: Reload systemd

- name: Start pt-agent service
  systemd:
    name: pt-agent
    state: started
  become: yes

- name: Enable pt-agent service
  systemd:
    name: pt-agent
    enabled: yes
  become: yes

handlers:
  - name: Reload systemd
    systemd:
      name: pt-agent
      state: reloaded
